#dist: xenial
language: python
python:
  - 3.7.6
#before_install:
  #- chmod +x manage.py
install:
  - pip install -r iaproject/requirements.txt
script:
  - SECRET_KEY="whatever" python iaproject/manage.py test

  #code from Anna_ci Slack